#!/usr/bin/env python3
"""One-shot patch: replace Denmark/Italy/France/Germany sections in descriptions.yml."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
YAML = ROOT / "_data/travel/descriptions.yml"


def entry(
    id_,
    title_en,
    title_zh,
    date,
    location_en,
    location_zh,
    weather_en,
    weather_zh,
    landmark_en,
    landmark_zh,
    description_en,
    description_zh,
):
    def q(s):
        return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'

    fields = [
        ("id", str(id_)),
        ("title_en", title_en),
        ("title_zh", title_zh),
        ("date", date),
        ("location_en", location_en),
        ("location_zh", location_zh),
        ("weather_en", weather_en),
        ("weather_zh", weather_zh),
        ("landmark_en", landmark_en),
        ("landmark_zh", landmark_zh),
        ("description_en", description_en),
        ("description_zh", description_zh),
    ]
    lines = ["  - id: " + str(id_)]
    for k, v in fields[1:]:
        lines.append(f"    {k}: {q(v)}")
    return "\n".join(lines)


def section(header, key, items):
    parts = [header, f"{key}:"]
    for item in items:
        parts.append(entry(**item))
    return "\n".join(parts) + "\n"


NOV_DENMARK = [
    dict(id_=1, title_en="Tivoli Gardens Main Entrance", title_zh="趣伏里公园主入口", date="Nov 2022",
         location_en="Copenhagen, Denmark", location_zh="丹麦 哥本哈根",
         weather_en="Overcast, cold", weather_zh="阴天，寒冷",
         landmark_en="Tivoli Gardens entrance", landmark_zh="趣伏里公园入口",
         description_en="The historic red-brick Tivoli facade rises under a flat grey sky, its rooftop TIVOLI sign mounted on a decorative metal framework. Poster boxes and green doors line the street while a modern glass building contrasts on the right.",
         description_zh="阴沉天空下，趣伏里公园红砖主立面格外醒目，屋顶 TIVOLI 招牌架在装饰性金属结构上。入口两侧是海报灯箱与绿色木门，右侧现代玻璃楼形成对比。"),
    dict(id_=2, title_en="Reformed Church on Gothersgade", title_zh="戈瑟斯路归正教会", date="Nov 2022",
         location_en="Copenhagen, Denmark", location_zh="丹麦 哥本哈根",
         weather_en="Sunny with light snow", weather_zh="晴朗，薄雪",
         landmark_en="Reformert Kirke", landmark_zh="归正教会",
         description_en="A crisp November morning on Gothersgade: the Reformed Church's green spire rises above red-brick rooftops dusted with snow. Parked cars and bicycles line the quiet street under a clear blue sky.",
         description_zh="十一月清晨的戈瑟斯路，归正教会绿色尖顶从覆雪红砖屋顶后升起。晴朗蓝天下，街道旁停着汽车与自行车，格外安静。"),
    dict(id_=3, title_en="St. Alban's Church and Frozen Moat", title_zh="圣阿尔班教堂与冰封护城河", date="Nov 2022",
         location_en="Churchillparken, Copenhagen", location_zh="丹麦 哥本哈根 丘吉尔公园",
         weather_en="Clear winter day, frozen", weather_zh="晴朗冬日，结冰",
         landmark_en="St. Alban's Church (Den Engelske Kirke)", landmark_zh="圣阿尔班教堂",
         description_en="St. Alban's tall dark spire stands beside a moat completely covered in snow and ice. Kastellet ramparts frame the scene while distant industrial chimneys release thin plumes of steam.",
         description_zh="圣阿尔班教堂高耸的深色尖塔旁，护城河完全被冰雪覆盖。卡斯特雷特土堤环绕四周，远处工业烟囱向清冷空气中吐出细细白烟。"),
    dict(id_=4, title_en="King's Gate at Kastellet", title_zh="卡斯特雷特国王门", date="Nov 2022",
         location_en="Kastellet, Copenhagen", location_zh="丹麦 哥本哈根 卡斯特雷特",
         weather_en="Clear and cold, light snow", weather_zh="晴朗寒冷，薄雪",
         landmark_en="Kastellet King's Gate", landmark_zh="卡斯特雷特国王门",
         description_en="Pedestrians cross a wooden bridge toward the stone King's Gate set into grassy ramparts. A leafless tree silhouettes against deep blue sky while frost edges the frozen moat.",
         description_zh="行人走过木桥，前往嵌入草坡的石头国王门。无叶大树在深蓝天空下形成剪影，结冰护城河边覆着薄霜。"),
    dict(id_=5, title_en="Sunset at Kongens Nytorv", title_zh="国王新广场黄昏", date="Nov 2022",
         location_en="Kongens Nytorv, Copenhagen", location_zh="丹麦 哥本哈根 国王新广场",
         weather_en="Overcast sunset, light snow", weather_zh="阴云日落，薄雪",
         landmark_en="Royal Danish Theatre and Christian V statue", landmark_zh="皇家丹麦剧院与克里斯蒂安五世骑马像",
         description_en="A family walks across snow-dusted cobblestones as the sun sinks behind the Royal Danish Theatre dome. The equestrian statue of Christian V and an ornate lamp post frame the backlit square.",
         description_zh="一家人走过覆着薄雪的鹅卵石广场，夕阳沉入皇家丹麦剧院圆顶之后。克里斯蒂安五世骑马像与复古路灯在逆光中勾勒出广场轮廓。"),
    dict(id_=6, title_en="Sunset from Kastellet Ramparts", title_zh="卡斯特雷特城墙上的落日", date="Nov 2022",
         location_en="Kastellet, Copenhagen", location_zh="丹麦 哥本哈根 卡斯特雷特",
         weather_en="Cold, dramatic cirrus clouds", weather_zh="寒冷，壮观卷云",
         landmark_en="Kastellet ramparts and city skyline", landmark_zh="卡斯特雷特城墙与城市天际线",
         description_en="Wispy cirrus clouds streak across the sky as the low November sun glows behind bare trees and a church spire. A metal railing and frost-dusted grass mark the view from the historic ramparts.",
         description_zh="卷云划过天空，十一月低垂的太阳在光秃树木与教堂尖顶后闪耀。金属栏杆与覆霜草坡标记着这段历史城墙上的眺望视角。"),
    dict(id_=7, title_en="Snowy Street in Copenhagen", title_zh="哥本哈根雪后街景", date="Nov 2022",
         location_en="Copenhagen, Denmark", location_zh="丹麦 哥本哈根",
         weather_en="Cold and clear with light snow", weather_zh="寒冷晴朗，薄雪",
         landmark_en="Traditional red-brick street", landmark_zh="传统红砖街道",
         description_en="A quiet side street lined with red-brick buildings shows a thin layer of snow on roofs and pavement. Wispy clouds drift across a pale sky as a white van recedes into the distance.",
         description_zh="红砖建筑夹道的安静侧街，屋顶与路面覆着薄雪。淡淡云彩掠过淡色天空，一辆白色货车驶向远处。"),
    dict(id_=8, title_en="Snowy Walk in a Residential Quarter", title_zh="住宅区雪后小径", date="Nov 2022",
         location_en="Copenhagen, Denmark", location_zh="丹麦 哥本哈根",
         weather_en="Overcast and cold with snow", weather_zh="阴冷，有积雪",
         landmark_en="Modern brick apartment blocks", landmark_zh="现代砖砌公寓楼",
         description_en="A person pushes a double stroller along a cleared path through a snow-covered field. Red-brick apartment buildings and bare trees surround the peaceful winter scene.",
         description_zh="一人推着双人婴儿车走在扫过雪的小径上，两侧是覆雪的草地。红砖公寓与光秃树木环绕，冬景宁静。"),
    dict(id_=9, title_en="With Hans Christian Andersen Statue", title_zh="安徒生雕像前合影", date="Nov 2022",
         location_en="Near City Hall, Copenhagen", location_zh="丹麦 哥本哈根 市政厅附近",
         weather_en="Overcast, cold with frost", weather_zh="阴天寒冷，有霜",
         landmark_en="Hans Christian Andersen statue", landmark_zh="安徒生雕像",
         description_en="A bronze Hans Christian Andersen in top hat and frock coat sits beside Copenhagen City Hall. Frost touches the grass as bare trees and traffic on H.C. Andersens Boulevard fill the background.",
         description_zh="戴高礼帽、穿长外套的安徒生铜像坐在哥本哈根市政厅旁。草上结霜，背景是光秃树木与安徒生大道上的车流。"),
    dict(id_=10, title_en="World Cup Third-Place Match Screening", title_zh="世界杯季军战观赛", date="Nov 2022",
         location_en="Copenhagen, Denmark", location_zh="丹麦 哥本哈根",
         weather_en="Indoor evening", weather_zh="室内，晚间",
         landmark_en="Public match viewing hall", landmark_zh="公共观赛大厅",
         description_en="Fans watch Croatia lead Morocco 2–1 on a large projector screen in a dim industrial hall. International flag bunting crosses the ceiling above long wooden picnic tables.",
         description_zh="球迷在昏暗的工业风大厅里通过投影观看克罗地亚2比1领先摩洛哥。长木桌上方天花板上挂满各国小旗。"),
    dict(id_=11, title_en="Round Tower (Rundetårn)", title_zh="哥本哈根圆塔", date="Nov 2022",
         location_en="Copenhagen, Denmark", location_zh="丹麦 哥本哈根",
         weather_en="Overcast, cold", weather_zh="阴天，寒冷",
         landmark_en="Rundetårn (Round Tower)", landmark_zh="圆塔",
         description_en="The cylindrical Round Tower rises beside Trinitatis Church under a grey sky. Pedestrians in winter coats and parked bicycles gather at the ornate arched entrance on wet cobblestones.",
         description_zh="圆柱形的圆塔在阴天里与三一教堂并肩而立。穿冬装的行人与停放的自行车聚集在湿鹅卵石路上的华丽拱门前。"),
    dict(id_=12, title_en="Harbor Portrait at Refshaleøen", title_zh="Refshaleøen 港口留影", date="Nov 2022",
         location_en="Refshaleøen, Copenhagen", location_zh="丹麦 哥本哈根 Refshaleøen",
         weather_en="Clear winter afternoon, snow", weather_zh="晴朗冬日下午，有雪",
         landmark_en="Refshaleøen harbor and wind turbines", landmark_zh="Refshaleøen 港口与风力发电机",
         description_en="A snow-dusted railing overlooks a marina where sailboats sit among patches of ice. Golden afternoon light hits industrial buildings marked Refshaleøen and distant wind turbines.",
         description_zh="覆雪的栏杆外是停满帆船的码头，水面部分结冰。午后金光洒在印有 Refshaleøen 的工业建筑与远处风力发电机上。"),
    dict(id_=13, title_en="Kastelskirken Courtyard", title_zh="卡斯特雷特教堂庭院", date="Nov 2022",
         location_en="Kastellet, Copenhagen", location_zh="丹麦 哥本哈根 卡斯特雷特",
         weather_en="Overcast with light snow", weather_zh="阴天，薄雪",
         landmark_en="Kastelskirken (Citadel Church)", landmark_zh="卡斯特雷特教堂",
         description_en="The pale-yellow Kastelskirken faces a wide courtyard dusted with snow, flanked by long red barracks and bare trees. Dramatic streaky clouds radiate from behind the central pediment.",
         description_zh="淡黄色卡斯特雷特教堂面向覆着薄雪的宽阔庭院，两侧是长长红砖营房与光秃树木。条纹状云层从中央三角楣后向四周散开。"),
    dict(id_=14, title_en="Stormgade at Sunset", title_zh="Stormgade 黄昏街景", date="Nov 2022",
         location_en="Stormgade, Copenhagen", location_zh="丹麦 哥本哈根 Stormgade",
         weather_en="Overcast with golden sunset", weather_zh="阴天，金色余晖",
         landmark_en="Ny Carlsberg Glyptotek", landmark_zh="新嘉士伯雕塑馆",
         description_en="Golden light filters through heavy clouds onto damp asphalt at the Stormgade intersection. The classical facade of the Ny Carlsberg Glyptotek glows on the right beside a blue bicycle lane.",
         description_zh="Stormgade 十字路口，金色光线穿过厚云照在潮湿路面上。右侧新嘉士伯雕塑馆古典立面在蓝色自行车道旁熠熠生辉。"),
    dict(id_=15, title_en="Ivar Huitfeldt Column", title_zh="伊瓦尔·维特费尔特纪念柱", date="Nov 2022",
         location_en="Langelinie, Copenhagen", location_zh="丹麦 哥本哈根 长堤公园",
         weather_en="Clear with wispy clouds", weather_zh="晴朗，薄云",
         landmark_en="Ivar Huitfeldt Column", landmark_zh="伊瓦尔·维特费尔特纪念柱",
         description_en="A low-angle view shows the green-patina Victory figure atop the Ivar Huitfeldt Column against a soft blue sky. Bare tree branches peek in at the edge of the frame.",
         description_zh="低角度仰望，绿色铜锈的胜利女神像矗立在纪念柱顶，背景是柔和蓝天，画面边缘露出光秃树枝。"),
    dict(id_=16, title_en="Winter Marina with CopenHill", title_zh="冬日码头与 CopenHill", date="Nov 2022",
         location_en="Copenhagen harbor", location_zh="丹麦 哥本哈根 港口",
         weather_en="Sunny and freezing, partial ice", weather_zh="晴朗严寒，部分结冰",
         landmark_en="Marina and CopenHill (Amager Bakke)", landmark_zh="游艇码头与 CopenHill 能源塔",
         description_en="Sailboats under tarps line a marina where thin ice forms on calm water. The distinctive CopenHill building and wind turbines stand on the distant shore under crisp winter light.",
         description_zh="盖着防雨布的帆船排列在码头，平静水面结起薄冰。远处标志性的 CopenHill 与风力发电机在清冽冬光下清晰可见。"),
    dict(id_=17, title_en="J.P.E. Hartmann Statue", title_zh="J.P.E. Hartmann 作曲家雕像", date="Nov 2022",
         location_en="Sankt Annæ Plads, Copenhagen", location_zh="丹麦 哥本哈根 圣安妮广场",
         weather_en="Sunny and cold with snow", weather_zh="晴朗寒冷，有雪",
         landmark_en="J.P.E. Hartmann monument", landmark_zh="J.P.E. Hartmann 纪念碑",
         description_en="The bronze composer Hartmann sits on a red granite pedestal in a snow-dusted square. Rows of pruned bare trees lead toward the Garrison Church spire under a deep blue sky.",
         description_zh="青铜作曲家 Hartmann 坐于红色花岗岩基座上，广场覆着薄雪。修剪过的光秃树列引向卫戍教堂尖顶，天空湛蓝。"),
    dict(id_=18, title_en="Frost on Kastellet Ramparts", title_zh="卡斯特雷特城墙薄霜", date="Nov 2022",
         location_en="Kastellet, Copenhagen", location_zh="丹麦 哥本哈根 卡斯特雷特",
         weather_en="Clear and cold with frost", weather_zh="晴朗寒冷，有霜",
         landmark_en="Kastellet earthworks", landmark_zh="卡斯特雷特土堤",
         description_en="Tiered grassy ramparts carry a dusting of frost beneath bare sentinel trees. A few walkers and an empty bench sit along the ridge under a vast pale sky.",
         description_zh="层层草坡土堤上覆着薄霜，光秃树木如哨兵伫立。几个人与一张空长椅在坡脊上，头顶是广阔淡色天空。"),
    dict(id_=19, title_en="Little Mermaid and CopenHill", title_zh="小美人鱼与 CopenHill", date="Nov 2022",
         location_en="Langelinie, Copenhagen", location_zh="丹麦 哥本哈根 长堤公园",
         weather_en="Overcast and cold", weather_zh="阴天，寒冷",
         landmark_en="The Little Mermaid and CopenHill", landmark_zh="小美人鱼像与 CopenHill",
         description_en="The Little Mermaid sits on her rock as steam rises from CopenHill across the harbor. A Danish flag flies over red-roofed buildings while ripples cover the grey water.",
         description_zh="小美人鱼静静坐在礁石上，对岸 CopenHill 烟囱冒着白烟。丹麦国旗在红顶建筑上方飘扬，灰色水面泛起涟漪。"),
    dict(id_=20, title_en="Selfie on Bredgade", title_zh="Bredgade 自拍", date="Nov 2022",
         location_en="Bredgade, Copenhagen", location_zh="丹麦 哥本哈根 Bredgade",
         weather_en="Bright and cold", weather_zh="明亮，寒冷",
         landmark_en="Alexander Nevsky Church and Metro sign", landmark_zh="亚历山大·涅夫斯基教堂与地铁标志",
         description_en="A street selfie captures ornate facades on Bredgade with the golden domes of Alexander Nevsky Church in the distance. A red Metro M sign marks the nearby Marmorkirken station.",
         description_zh="Bredgade 街景自拍，远处可见亚历山大·涅夫斯基教堂金色圆顶。红色地铁 M 标志指向附近的大理石教堂站。"),
    dict(id_=21, title_en="Hans Christian Andersen by City Hall", title_zh="市政厅旁安徒生雕像", date="Nov 2022",
         location_en="Copenhagen City Hall area", location_zh="丹麦 哥本哈根 市政厅一带",
         weather_en="Overcast with frost", weather_zh="阴天，有霜",
         landmark_en="Hans Christian Andersen statue and City Hall", landmark_zh="安徒生雕像与市政厅",
         description_en="The seated Andersen statue looks toward H.C. Andersens Boulevard from beside the red-brick City Hall. Frost on cobblestones and leafless trees mark a quiet November afternoon.",
         description_zh="坐姿安徒生雕像在红砖市政厅旁望向安徒生大道。鹅卵石上的霜与无叶树木标记着安静的十一月午后。"),
    dict(id_=22, title_en="Frozen Moat at Kastellet", title_zh="卡斯特雷特冰封护城河", date="Nov 2022",
         location_en="Kastellet, Copenhagen", location_zh="丹麦 哥本哈根 卡斯特雷特",
         weather_en="Sunny winter day", weather_zh="晴朗冬日",
         landmark_en="Kastellet moat and ramparts", landmark_zh="卡斯特雷特护城河与土堤",
         description_en="A figure in a long black coat stands before a fully frozen moat. Snow-dusted ramparts and bare trees line the horizon under a bright blue sky with wispy clouds.",
         description_zh="穿长款黑大衣的人站在完全冻结的护城河前。覆雪土堤与光秃树木在明亮蓝天和薄云下延伸。"),
    dict(id_=23, title_en="Golden Hour on a Shopping Side Street", title_zh="购物小巷的黄金时刻", date="Nov 2022",
         location_en="Central Copenhagen", location_zh="丹麦 哥本哈根 市中心",
         weather_en="Overcast with sunset glow", weather_zh="阴天，夕阳余晖",
         landmark_en="Moss Copenhagen and Normal stores", landmark_zh="Moss Copenhagen 与 Normal 商店",
         description_en="Low sun glows at the end of a narrow cobblestone lane between Moss Copenhagen and Normal shops. Red no-entry signs and parked bicycles mark a quiet Strøget side street.",
         description_zh="狭窄鹅卵石小巷尽头，夕阳在 Moss Copenhagen 与 Normal 店之间洒下暖光。红色禁行标志与停放自行车标记着 Strøget 旁一条安静支路。"),
    dict(id_=24, title_en="Ny Carlsberg Glyptotek at Dusk", title_zh="嘉士伯雕塑馆黄昏", date="Nov 2022",
         location_en="Copenhagen, Denmark", location_zh="丹麦 哥本哈根",
         weather_en="Cloudy sunset", weather_zh="多云日落",
         landmark_en="Ny Carlsberg Glyptotek", landmark_zh="新嘉士伯雕塑馆",
         description_en="Cars wait at an intersection as the Glyptotek's green dome stands out against dramatic clouds. Bare trees and overhead tram wires frame the transition into evening.",
         description_zh="车辆在路口等候，雕塑馆绿色圆顶在戏剧性云层映衬下格外醒目。光秃树木与电车架空线框住入夜时分。"),
    dict(id_=25, title_en="Winter Twilight over Copenhagen Harbor", title_zh="哥本哈根港口冬夜", date="Nov 2022",
         location_en="Copenhagen harbor", location_zh="丹麦 哥本哈根 港口",
         weather_en="Overcast twilight, light snow", weather_zh="阴云黄昏，薄雪",
         landmark_en="Copenhagen Opera House and Holmen", landmark_zh="哥本哈根歌剧院与霍尔门",
         description_en="Golden light on the horizon silhouettes the Opera House and naval vessels across the harbor. A dusting of snow covers the wooden pier in the foreground.",
         description_zh="地平线金色余晖勾勒出歌剧院与海军舰艇的剪影。前景木码头覆着薄薄一层雪。"),
    dict(id_=26, title_en="Afternoon at Nyhavn", title_zh="新港午后", date="Nov 2022",
         location_en="Nyhavn, Copenhagen", location_zh="丹麦 哥本哈根 新港",
         weather_en="Overcast with soft light", weather_zh="阴天，柔光",
         landmark_en="Nyhavn canal and colorful townhouses", landmark_zh="新港运河与彩色房屋",
         description_en="Warm light touches terracotta and yellow facades along Nyhavn as the IVA II restaurant boat and traditional masts reflect in calm green water.",
         description_zh="柔和光线掠过新港陶土色与黄色立面，IVA II 餐厅船与传统桅杆倒映在平静绿水之中。"),
    dict(id_=27, title_en="The Marble Church (Marmorkirken)", title_zh="大理石教堂", date="Nov 2022",
         location_en="Copenhagen, Denmark", location_zh="丹麦 哥本哈根",
         weather_en="Clear and cold", weather_zh="晴朗，寒冷",
         landmark_en="Frederik's Church (Marmorkirken)", landmark_zh="腓特烈教堂（大理石教堂）",
         description_en="The green copper dome and columned portico of Marmorkirken dominate a city intersection. Pedestrians in heavy coats cross the street beneath the gilded inscription on the facade.",
         description_zh="绿色铜顶圆顶与柱廊在大理石教堂占据街角。穿厚外套的行人在立面金色铭文下穿过马路。"),
    dict(id_=28, title_en="View toward City Hall Square", title_zh="远眺市政厅广场", date="Nov 2022",
         location_en="Rådhuspladsen area, Copenhagen", location_zh="丹麦 哥本哈根 市政厅广场一带",
         weather_en="Overcast, damp", weather_zh="阴天，潮湿",
         landmark_en="Copenhagen City Hall and Lur Blowers statue", landmark_zh="哥本哈根市政厅与吹号人雕像",
         description_en="Copenhagen City Hall's clock tower rises on the right as bicycles line the sidewalk near Scandic Palace Hotel. The Lur Blowers column stands between wet cobblestones under a grey sky.",
         description_zh="右侧哥本哈根市政厅钟楼高耸，斯堪的克皇宫酒店旁人行道停满自行车。吹号人纪念柱立在潮湿鹅卵石路与阴沉天空之间。"),
    dict(id_=29, title_en="City Hall Square from Below", title_zh="仰拍市政厅广场", date="Nov 2022",
         location_en="Rådhuspladsen, Copenhagen", location_zh="丹麦 哥本哈根 市政厅广场",
         weather_en="Heavy overcast", weather_zh="浓云密布",
         landmark_en="City Hall, Lurblæserne, Scandic Palace", landmark_zh="市政厅、吹号人雕像、斯堪的克皇宫酒店",
         description_en="A low-angle view silhouettes the Lur Blowers monument between City Hall and Scandic Palace Hotel. A Ukrainian flag flies from a rooftop against thick November clouds.",
         description_zh="低角度仰拍，吹号人雕像在市政厅与斯堪的克皇宫酒店之间形成剪影。屋顶乌克兰国旗在厚重十一月云层下飘扬。"),
    dict(id_=30, title_en="St. Alban's Church in Winter Sun", title_zh="冬日阳光下的圣阿尔班教堂", date="Nov 2022",
         location_en="Kastellet area, Copenhagen", location_zh="丹麦 哥本哈根 卡斯特雷特一带",
         weather_en="Clear with light snow", weather_zh="晴朗，薄雪",
         landmark_en="St. Alban's Church", landmark_zh="圣阿尔班教堂",
         description_en="The slender flint-stone spire of St. Alban's Church rises above snow-dusted slopes. A yellow building with blue flags and wet cobblestones complete the crisp winter scene.",
         description_zh="燧石尖塔的圣阿尔班教堂从覆雪坡地上升起。黄色建筑上蓝旗飘扬，湿鹅卵石地面完成这幅清冽冬景。"),
    dict(id_=31, title_en="World Cup Final Moments on Screen", title_zh="世界杯比赛最后时刻", date="Nov 2022",
         location_en="Copenhagen, Denmark", location_zh="丹麦 哥本哈根",
         weather_en="Indoor evening", weather_zh="室内，晚间",
         landmark_en="Fan viewing venue", landmark_zh="球迷观赛场所",
         description_en="Young fans watch the closing minutes of a World Cup match as Croatian players in checkered jerseys fill the projector screen. Flag bunting and wooden benches create a communal atmosphere.",
         description_zh="年轻球迷观看世界杯比赛尾声，投影屏上克罗地亚格子球衣球员清晰可见。旗饰与木凳营造出集体观赛氛围。"),
    dict(id_=32, title_en="Royal Danish Theatre at Sunset", title_zh="皇家丹麦剧院日落", date="Nov 2022",
         location_en="Kongens Nytorv, Copenhagen", location_zh="丹麦 哥本哈根 国王新广场",
         weather_en="Overcast with low sun, frost", weather_zh="阴天低阳，有霜",
         landmark_en="Royal Danish Theatre and Christian V statue", landmark_zh="皇家丹麦剧院与克里斯蒂安五世骑马像",
         description_en="The theatre dome is backlit as the equestrian statue of Christian V stands in silhouette. Light frost on the square and a green lens flare add to the chilly late-November mood.",
         description_zh="剧院圆顶被逆光勾勒，克里斯蒂安五世骑马像成剪影。广场薄霜与绿色镜头光晕增添十一月傍晚寒意。"),
    dict(id_=33, title_en="Kongens Nytorv in Winter", title_zh="国王新广场冬景", date="Nov 2022",
         location_en="Kongens Nytorv, Copenhagen", location_zh="丹麦 哥本哈根 国王新广场",
         weather_en="Overcast with snow on gardens", weather_zh="阴天，花园有雪",
         landmark_en="Royal Danish Theatre and square gardens", landmark_zh="皇家丹麦剧院与广场花园",
         description_en="Snow covers the central gardens of Kongens Nytorv while wet cobblestones curve past benches and a red market hut. The theatre dome sits under a heavy grey sky.",
         description_zh="国王新广场中央花园覆雪，湿鹅卵石路绕过长椅与红色集市小亭。剧院圆顶在厚重灰云下静立。"),
    dict(id_=34, title_en="Sunny Frost at Kastellet", title_zh="卡斯特雷特晴冬薄霜", date="Nov 2022",
         location_en="Kastellet, Copenhagen", location_zh="丹麦 哥本哈根 卡斯特雷特",
         weather_en="Clear and cold with frost", weather_zh="晴朗寒冷，有霜",
         landmark_en="Kastellet ramparts", landmark_zh="卡斯特雷特城墙",
         description_en="Bare trees silhouette sharply against deep blue sky above frost-lined ramparts. A red-tiled roof peeks over the grassy earthworks in bright November afternoon light.",
         description_zh="无叶树木在深蓝天空下形成清晰剪影，覆霜土堤延伸远方。明亮十一月午后，红砖屋顶从草坡后探出。"),
    dict(id_=35, title_en="Twilight over Kastellet Ramparts", title_zh="卡斯特雷特黄昏", date="Nov 2022",
         location_en="Kastellet, Copenhagen", location_zh="丹麦 哥本哈根 卡斯特雷特",
         weather_en="Cold twilight with frost", weather_zh="寒冷黄昏，有霜",
         landmark_en="Ramparts and distant church spire", landmark_zh="土堤与远处教堂尖塔",
         description_en="Two figures in winter coats pause at a railing as golden light fades over frost-dusted embankments. A church spire punctuates the distant skyline beneath streaky clouds.",
         description_zh="两个穿冬大衣的人停在栏杆旁，金色余晖在覆霜土堤上消退。条纹云下，远处天际线点缀着教堂尖塔。"),
    dict(id_=36, title_en="World Cup Viewing Selfie", title_zh="世界杯观赛自拍", date="Nov 2022",
         location_en="Copenhagen, Denmark", location_zh="丹麦 哥本哈根",
         weather_en="Indoor evening", weather_zh="室内，晚间",
         landmark_en="Public match screening", landmark_zh="公共观赛活动",
         description_en="Two friends give thumbs-up in front of a large screen showing a World Cup match, with medics attending a player on the pitch. International flags hang above crowded wooden tables.",
         description_zh="两位朋友在世界杯大屏幕前竖起大拇指，场上球员正接受医疗人员照料。拥挤木桌上方悬挂各国国旗。"),
]

OCT_ITALY = [
    dict(id_=1, title_en="Canal in the Rain, Venice", title_zh="威尼斯雨中运河", date="Oct 2022",
         location_en="Venice, Italy", location_zh="意大利 威尼斯",
         weather_en="Rainy and overcast", weather_zh="下雨，阴天",
         landmark_en="Venetian canal and bridge", landmark_zh="威尼斯运河与拱桥",
         description_en="From an elevated walkway, a blue transport boat heads toward an arched bridge while pedestrians with umbrellas pass moored gondolas. Heavy grey clouds and wet paving mark a rainy October day.",
         description_zh="从高处步道望去，蓝白交通船驶向拱桥，撑伞行人经过停泊的贡多拉。厚重灰云与湿路面标记着十月雨天。"),
    dict(id_=2, title_en="Wide Canal with Arched Bridges", title_zh="拱桥间的宽阔运河", date="Oct 2022",
         location_en="Venice, Italy", location_zh="意大利 威尼斯",
         weather_en="Overcast", weather_zh="阴天",
         landmark_en="Venetian canal and bridges", landmark_zh="威尼斯运河与拱桥",
         description_en="A white motorboat cruises toward the camera between terracotta and ochre palazzi. Two stone footbridges span the canal in the distance under a uniform grey sky.",
         description_zh="白色摩托艇在陶土色与赭黄色宫殿间驶来，远处两座石桥横跨运河，天空一片灰蒙。"),
    dict(id_=3, title_en="Canal Traffic from a Bridge", title_zh="桥上俯瞰运河交通", date="Oct 2022",
         location_en="Venice, Italy", location_zh="意大利 威尼斯",
         weather_en="Overcast", weather_zh="阴天",
         landmark_en="Side canal in Venice", landmark_zh="威尼斯支渠",
         description_en="Motorboats navigate a narrow canal between weathered brick facades with green shutters. A figure in a bright pink jacket stands at the helm of a small blue boat.",
         description_zh="摩托艇在斑驳砖墙与绿色百叶窗之间的窄渠穿行，一艘蓝色小船上站着穿亮粉色夹克的人。"),
    dict(id_=4, title_en="Quiet Side Canal", title_zh="宁静的后巷运河", date="Oct 2022",
         location_en="Venice, Italy", location_zh="意大利 威尼斯",
         weather_en="Overcast with soft sunlight", weather_zh="阴天，柔光",
         landmark_en="Residential canal", landmark_zh="民居运河",
         description_en="A still side canal reflects aged plaster and brick under muted sunlight. Mooring poles and a glass-enclosed balcony add texture to the empty waterway.",
         description_zh="安静支渠映着斑驳灰泥与砖墙，柔和天光下无船无人。系船柱与玻璃封闭阳台为水面增添层次。"),
    dict(id_=5, title_en="Bridge of Sighs", title_zh="叹息桥", date="Oct 2022",
         location_en="Venice, Italy", location_zh="意大利 威尼斯",
         weather_en="Overcast", weather_zh="阴天",
         landmark_en="Ponte dei Sospiri (Bridge of Sighs)", landmark_zh="叹息桥",
         description_en="The white limestone Bridge of Sighs spans the Rio di Palazzo between the Doge's Palace and the New Prison. Dark canal water and a distant footbridge complete the somber scene.",
         description_zh="白色石灰岩叹息桥横跨宫殿河，连接总督府与新监狱。深色运河水与远处人行桥完成这幅沉静画面。"),
    dict(id_=6, title_en="Giudecca Waterfront and Il Redentore", title_zh="朱代卡水岸与救主堂", date="Oct 2022",
         location_en="Venice, Italy", location_zh="意大利 威尼斯",
         weather_en="Overcast", weather_zh="阴天",
         landmark_en="Church of the Redeemer (Il Redentore)", landmark_zh="威尼斯救主堂",
         description_en="A motorboat crosses the Giudecca Canal toward the domed Il Redentore church. Terracotta rooftops line the waterfront under a heavy autumn sky.",
         description_zh="摩托艇划过朱代卡运河，驶向圆顶救主堂。陶土色屋顶沿水岸排列，头顶是阴沉秋空。"),
    dict(id_=7, title_en="Santo Stefano Church and Leaning Campanile", title_zh="圣斯蒂法诺教堂与斜塔", date="Oct 2022",
         location_en="Venice, Italy", location_zh="意大利 威尼斯",
         weather_en="Sunny", weather_zh="晴朗",
         landmark_en="Chiesa di Santo Stefano", landmark_zh="圣斯蒂法诺教堂",
         description_en="Red-brick Gothic facades and a famous leaning campanile glow in strong sunlight. A rose window and white stone portal anchor the church on a bright campo.",
         description_zh="红砖哥特立面与著名斜塔在强烈日光下熠熠生辉。玫瑰窗与白色石门框锚定这座明亮 campo 上的教堂。"),
    dict(id_=8, title_en="Classical Facade with Italian Flags", title_zh="悬挂国旗的古典立面", date="Oct 2022",
         location_en="Venice, Italy", location_zh="意大利 威尼斯",
         weather_en="Sunny with wispy clouds", weather_zh="晴朗，薄云",
         landmark_en="Renaissance palazzo", landmark_zh="文艺复兴宫邸",
         description_en="Istrian stone pilasters and arched windows rise beneath Italian and EU flags. A seagull crosses the bright blue sky above ornate carved friezes.",
         description_zh="伊斯特里亚石圆柱与拱窗立面下悬挂意大利与欧盟旗帜。海鸥飞过湛蓝天空，掠过精美石雕饰带。"),
    dict(id_=9, title_en="St. Mark's Clock Tower", title_zh="圣马可时钟塔", date="Oct 2022",
         location_en="St. Mark's Square, Venice", location_zh="意大利 威尼斯 圣马可广场",
         weather_en="Overcast", weather_zh="阴天",
         landmark_en="Torre dell'Orologio", landmark_zh="圣马可时钟塔",
         description_en="The astronomical clock and golden Winged Lion of Saint Mark decorate the Renaissance tower facade. An arched passageway to the Merceria opens beneath heavy clouds.",
         description_zh="天文钟与金色圣马可飞狮装饰文艺复兴塔楼立面。厚重云层下，通向 Merceria 购物街的拱形通道敞开。"),
    dict(id_=10, title_en="Rialto Bridge and Gondola", title_zh="里亚托桥与贡多拉", date="Oct 2022",
         location_en="Grand Canal, Venice", location_zh="意大利 威尼斯 大运河",
         weather_en="Overcast", weather_zh="阴天",
         landmark_en="Rialto Bridge (Ponte di Rialto)", landmark_zh="里亚托桥",
         description_en="A gondola with passengers glides below the white stone arch of the Rialto Bridge. Colorful palazzi and a distant campanile line the Grand Canal on a grey October day.",
         description_zh="载有乘客的贡多拉滑过里亚托桥白色石拱下方。彩色宫殿与远处钟楼沿大运河排列，十月天色灰蒙。"),
    dict(id_=11, title_en="On the Rialto Bridge Steps", title_zh="里亚托桥台阶上", date="Oct 2022",
         location_en="Venice, Italy", location_zh="意大利 威尼斯",
         weather_en="Bright but hazy", weather_zh="明亮，有薄雾",
         landmark_en="Rialto Bridge", landmark_zh="里亚托桥",
         description_en="A portrait on the weathered stone steps of the Rialto Bridge with white balustrades and a church dome visible behind colorful buildings. Other tourists climb the stairs in the background.",
         description_zh="里亚托桥风化石阶上的留影，白色栏杆与彩色建筑后的教堂圆顶可见。背景里其他游客正拾级而上。"),
    dict(id_=12, title_en="Group Photo with San Giorgio Maggiore", title_zh="与圣乔治·马焦雷教堂合影", date="Oct 2022",
         location_en="Venice lagoon waterfront", location_zh="意大利 威尼斯 潟湖水岸",
         weather_en="Overcast and cool", weather_zh="阴天，凉爽",
         landmark_en="San Giorgio Maggiore", landmark_zh="圣乔治·马焦雷教堂",
         description_en="Five friends pose on a wooden pier flanked by mooring poles as San Giorgio Maggiore rises across turquoise water. Everyone wears thick jackets under a cloudy sky.",
         description_zh="五位好友在木码头合影，两侧是系船柱，碧绿海水对岸圣乔治·马焦雷教堂清晰可见。阴天下大家都穿着厚外套。"),
]

# Continue in part 2 - France and Germany loaded from companion file
exec((ROOT / "scripts" / "patch_travel_captions_part2.py").read_text(encoding="utf-8"), globals())

def main():
    finland = YAML.read_text(encoding="utf-8").split("### 🇩🇰 Denmark")[0].rstrip() + "\n"
    out = finland
    out += section("### 🇩🇰 Denmark (Nov 2022)", "nov_denmark", NOV_DENMARK)
    out += section("### 🇮🇹 Italy (Oct 2022)", "oct_italy", OCT_ITALY)
    out += section("### 🇫🇷 France (Sep 2022)", "sep_france", SEP_FRANCE)
    out += section("### 🇩🇪 Germany (Aug 2022)", "aug_germany", AUG_GERMANY)
    YAML.write_text(out, encoding="utf-8")
    print(f"Wrote {YAML} ({len(out.splitlines())} lines)")


if __name__ == "__main__":
    main()
